language: c

compiler: gcc

before_install:
  - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded

install:
  - sudo apt-get update
  - sudo apt-get install -y gcc-arm-none-eabi

script:
  - make

env:
  matrix:
    - VARIANT_NAME=arduino_due
    - VARIANT_NAME=atmel_sam4s_xplained
    - VARIANT_NAME=atmel_sam4s_xplained_pro
    - VARIANT_NAME=atmel_sam4s_wpir_rd
    - VARIANT_NAME=atmel_sam4e_xplained_pro
    - VARIANT_NAME=atmel_samg55_xplained_pro

#addons:
#  apt:
#    sources:
#      - gcc-arm-embedded
#    packages:
#      - gcc-arm-none-eabi

#deploy:
#  provider: releases
#  api_key:
#    secure:
#  file:
#    -
#  skip_cleanup: true
#  on:
#    tags: true
#    repo: aethaniel/ExperimentalCore-sam
