language: c

compiler: gcc

# use containers
sudo: false

#
#before_install:
#  - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded

install:
  - wget https://launchpad.net/gcc-arm-embedded/4.9/4.9-2015-q3-update/+download/gcc-arm-none-eabi-4_9-2015q3-20150921-linux.tar.bz2
  - tar -xf gcc-arm-none-eabi-4_9-2015q3-20150921-linux.tar.bz2

addons:
  apt_packages:
    - lib32bz2-1.0
    - lib32ncurses5
    - lib32z1
    - cppcheck

script:
  - make

env:
  global:
    - PATH=/home/travis/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/travis/gcc-arm-none-eabi-4_9-2015q3/bin

  matrix:
    - VARIANT_NAME=arduino_due
    - VARIANT_NAME=atmel_sam4s_xplained
    - VARIANT_NAME=atmel_sam4s_xplained_pro
    - VARIANT_NAME=atmel_sam4s_wpir_rd
    - VARIANT_NAME=atmel_sam4e_xplained_pro
    - VARIANT_NAME=atmel_samg55_xplained_pro
    - VARIANT_NAME=logos_arachnio_due
    - VARIANT_NAME=poppy_core

#addons:
#  apt:
#    sources:
#      - gcc-arm-embedded
#    packages:
#      - gcc-arm-none-eabi

#deploy:
#  provider: releases
#  user: "GITHUB USERNAME"
#  password: "GITHUB PASSWORD"
#  file: "FILE TO UPLOAD"
#  skip_cleanup: true
#  on:
#    tags: true
